name: Hourly AQI Pipeline

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:

jobs:
  run-aqi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run AQI prediction
        run: |
          python -c "
          from pipelines.inference import predict_multi_aqi;
          print(predict_multi_aqi([1,6,24]))
          "